# Load Numpy

In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3,4], dtype='int32')
print(a)

[1 2 3 4]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# To check the dimension of the array:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
# TO check the shape 
a.shape

(4,)

In [7]:
b.shape

(2, 3)

In [8]:
# Get the total number of elements
a.size

4

In [ ]:
# Accessing/Changing specific elements, rows, columns, etc

In [11]:
z = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(z)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [13]:
# To get a specific element [row, column]
z[1, 5]

16

In [15]:
# to get a specific row 
z[0, :] # it will get us the complete first row with all its columns

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# to get a specific column:
z[:,0]  

array([ 1, 11])

In [17]:
# Getting start with [startindex:endindex:stepsize]
z[0, 1:-1:2]    # it will work on first row starting from second element to last element, with a step size=2

array([2, 4, 6, 8])

In [18]:
z[1, 0::] # it will get us all the elements of second row

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
z[1, 0::]==z[1,:]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [20]:
# we can replace the elements:
z[0,1]=-1
z

array([[ 1, -1,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [22]:
# we can do the above with a series of numbers
z[:,2]=5
z

array([[ 1, -1,  5,  4,  5,  6,  7,  8,  9, 10],
       [11, 12,  5, 14, 15, 16, 17, 18, 19, 20]])

In [23]:
z[1,:]=0
z

array([[ 1, -1,  5,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

### 3-d example

In [2]:
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
# Getting a specific element
x[0,1,1]

5

In [8]:
x[0,:,:] 

array([[1, 2, 3],
       [4, 5, 6]])

### Different kind of arrays

In [9]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# All 1's matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# to get a 3-d matrix 
np.ones((1,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
# any number matrix
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [18]:
# random decimal numbers
np.random.rand(3,2)

array([[3.56612715e-01, 3.80993106e-01],
       [2.72250422e-01, 8.24150939e-01],
       [8.87286391e-01, 4.80181758e-04]])

In [23]:
# random integers values
np.random.randint(1,8, size=(3,3)) # it will give us 3*3 array elements valued between 1 to 8

array([[5, 1, 4],
       [4, 3, 4],
       [7, 5, 1]])

In [24]:
# identity matrix --it is such a matrix where all elements are zero except the diagonal elements in this case it is 1.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
array = np.array([[1,2,3,4]])
repeat = np.repeat(array,4)
print(repeat)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]


In [27]:
array = np.array([[1,2,3,4]])
repeat = np.repeat(array,4, axis=0)
print(repeat)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [28]:
array = np.array([[1,2,3,4]])
repeat = np.repeat(array,4, axis=1)
print(repeat)

[[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]]


###  Mathematics

In [29]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [30]:
a-2

array([-1,  0,  1,  2,  3,  4])

In [31]:
a + 2

array([3, 4, 5, 6, 7, 8])

In [32]:
a ** 2

array([ 1,  4,  9, 16, 25, 36])

In [34]:
#taking sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

### Linear Algebra & Stats

In [37]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

c = np.matmul(a,b) # To perform matrix multiplication, the first matrix must have the same number of columns 
#as the second matrix has row
c

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [38]:
# Find the determinant
d = np.identity(3)
np.linalg.det(d)

1.0

In [39]:
s = np.array([[1,2,3,4],[5,6,7,8]])
s

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
np.min(s)

1

In [41]:
np.max(s)

8

In [43]:
np.max(s, axis=1) # return the max value along its rows

array([4, 8])

In [45]:
np.max(s, axis=0) # return the max value along its cloumns

array([5, 6, 7, 8])

### Reorganizing the Arrays

In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [56]:
# can also convert it into 3-d 
aft = before.reshape(2,2,2)
print(aft)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# Vertically Stacking:

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
# Horizontal stack:

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
# Horizontal stack:

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [65]:
np.hstack([h2,h1])

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [3]:
#Arange method
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Selection 



In [5]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [7]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [9]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])